import { TEAM_IDS, type TournamentSeed } from "./seed-formats-shared";

/**
 * Les deux étapes du Spike Tour, en démonstration.
 *
 * Le qualifier ne joue que trois rondes suisses au lieu des six du règlement :
 * à huit équipes, six tours rejoueraient les mêmes affiches. Les scores de
 * rounds sont saisis map par map, sans quoi le classement de l'article 7 n'a
 * rien à départager — c'est tout l'intérêt de ce jeu de démonstration.
 *
 * Le classement qui en sort, à dessein :
 *   1. seed 0 (3 pts) ;
 *   2. seeds 1, 3 et 2 à 2 points, séparés par le Buchholz (5, 4, 2) ;
 *   3. seeds 4 et 6 à 1 point et à Buchholz égal (6), séparés par la
 *      différence de rounds (−4 contre −7).
 * Les quatre premiers — 0, 1, 3, 2 — se retrouvent dans l'arbre Radiant.
 */
export const SPIKE_TOUR_QUALIFIER_SEED: TournamentSeed = {
  id: "fmt-spike-qualifier",
  name: "Spike Tour - Open Qualifier #1",
  format: "SPIKE_TOUR_QUALIFIER",
  status: "FINISHED",
  description:
    "Trois rondes suisses en Bo1, puis l'arbre Radiant à élimination directe en Bo3. Les demi-finalistes filent en Playoffs.",
  prizePool: "Qualification pour les Playoffs Radiant",
  bestOf: 1,
  teams: [0, 1, 2, 3, 4, 5, 6, 7],
  startDay: 80,
  endDay: 81,
  matches: [
    // Ronde 1 : appariement par seed, moitié haute contre moitié basse.
    {
      key: "r1-1",
      stage: "GROUP",
      round: "Ronde 1",
      a: 0,
      b: 4,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Ascent", 13, 8]],
    },
    {
      key: "r1-2",
      stage: "GROUP",
      round: "Ronde 1",
      a: 1,
      b: 5,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Bind", 13, 10]],
    },
    {
      key: "r1-3",
      stage: "GROUP",
      round: "Ronde 1",
      a: 2,
      b: 6,
      sa: 0,
      sb: 1,
      status: "FINISHED",
      day: 80,
      maps: [["Haven", 11, 13]],
    },
    {
      key: "r1-4",
      stage: "GROUP",
      round: "Ronde 1",
      a: 3,
      b: 7,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Split", 13, 6]],
    },
    // Ronde 2 : vainqueurs entre eux, perdants entre eux.
    {
      key: "r2-1",
      stage: "GROUP",
      round: "Ronde 2",
      a: 0,
      b: 1,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Lotus", 13, 11]],
    },
    {
      key: "r2-2",
      stage: "GROUP",
      round: "Ronde 2",
      a: 6,
      b: 3,
      sa: 0,
      sb: 1,
      status: "FINISHED",
      day: 80,
      maps: [["Sunset", 9, 13]],
    },
    {
      key: "r2-3",
      stage: "GROUP",
      round: "Ronde 2",
      a: 4,
      b: 5,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Abyss", 13, 9]],
    },
    {
      key: "r2-4",
      stage: "GROUP",
      round: "Ronde 2",
      a: 2,
      b: 7,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Corrode", 13, 7]],
    },
    // Ronde 3 : elle décide des quatre qualifiés pour l'arbre Radiant.
    {
      key: "r3-1",
      stage: "GROUP",
      round: "Ronde 3",
      a: 0,
      b: 3,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Ascent", 13, 10]],
    },
    {
      key: "r3-2",
      stage: "GROUP",
      round: "Ronde 3",
      a: 1,
      b: 6,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Bind", 13, 8]],
    },
    {
      key: "r3-3",
      stage: "GROUP",
      round: "Ronde 3",
      a: 4,
      b: 2,
      sa: 0,
      sb: 1,
      status: "FINISHED",
      day: 80,
      maps: [["Haven", 10, 13]],
    },
    {
      key: "r3-4",
      stage: "GROUP",
      round: "Ronde 3",
      a: 5,
      b: 7,
      sa: 1,
      sb: 0,
      status: "FINISHED",
      day: 80,
      maps: [["Split", 13, 11]],
    },
    // Arbre Radiant, le dimanche : les quatre premiers, en Bo3.
    {
      key: "rad-sf1",
      round: "Demi-finales",
      pos: 1,
      a: 0,
      b: 2,
      sa: 2,
      sb: 1,
      bestOf: 3,
      status: "FINISHED",
      day: 81,
      maps: [
        ["Lotus", 13, 11],
        ["Icebox", 9, 13],
        ["Pearl", 13, 8],
      ],
    },
    {
      key: "rad-sf2",
      round: "Demi-finales",
      pos: 2,
      a: 1,
      b: 3,
      sa: 1,
      sb: 2,
      bestOf: 3,
      status: "FINISHED",
      day: 81,
      maps: [
        ["Breeze", 13, 9],
        ["Fracture", 11, 13],
        ["Ascent", 10, 13],
      ],
    },
    {
      key: "rad-f",
      round: "Finale",
      pos: 1,
      a: 0,
      b: 3,
      sa: 2,
      sb: 0,
      bestOf: 3,
      status: "FINISHED",
      day: 81,
      maps: [
        ["Sunset", 13, 7],
        ["Abyss", 13, 10],
      ],
    },
  ],
};

/**
 * Les Playoffs Radiant : huit équipes, double élimination, Bo3 partout — les
 * quatre qualifiés de chaque Open Qualifier. La grande finale reste à jouer,
 * pour que le tournoi ait un match à venir à afficher.
 */
export const SPIKE_TOUR_PLAYOFFS_SEED: TournamentSeed = {
  id: "fmt-spike-playoffs",
  name: "Spike Tour - Playoffs Radiant",
  format: "SPIKE_TOUR_PLAYOFFS",
  status: "ONGOING",
  description:
    "Les huit qualifiés des deux Open Qualifiers, en double élimination et en Bo3. Grande finale à venir.",
  prizePool: "20 000 €",
  bestOf: 3,
  teams: [0, 1, 2, 3, 4, 5, 6, 7],
  startDay: 90,
  endDay: 94,
  matches: [
    {
      key: "ub-qf1",
      round: "UB Quarts de finale",
      pos: 1,
      a: 0,
      b: 7,
      sa: 2,
      sb: 0,
      status: "FINISHED",
      day: 90,
    },
    {
      key: "ub-qf2",
      round: "UB Quarts de finale",
      pos: 2,
      a: 3,
      b: 4,
      sa: 1,
      sb: 2,
      status: "FINISHED",
      day: 90,
    },
    {
      key: "ub-qf3",
      round: "UB Quarts de finale",
      pos: 3,
      a: 1,
      b: 6,
      sa: 2,
      sb: 1,
      status: "FINISHED",
      day: 91,
    },
    {
      key: "ub-qf4",
      round: "UB Quarts de finale",
      pos: 4,
      a: 2,
      b: 5,
      sa: 2,
      sb: 0,
      status: "FINISHED",
      day: 91,
    },
    {
      key: "ub-sf1",
      round: "UB Demi-finales",
      pos: 1,
      a: 0,
      b: 4,
      sa: 2,
      sb: 1,
      status: "FINISHED",
      day: 92,
    },
    {
      key: "ub-sf2",
      round: "UB Demi-finales",
      pos: 2,
      a: 1,
      b: 2,
      sa: 0,
      sb: 2,
      status: "FINISHED",
      day: 92,
    },
    {
      key: "ub-f",
      round: "UB Finale",
      pos: 1,
      a: 0,
      b: 2,
      sa: 2,
      sb: 1,
      status: "FINISHED",
      day: 93,
    },
    {
      key: "lb-r1-1",
      round: "LB Round 1",
      pos: 1,
      a: 7,
      b: 3,
      sa: 0,
      sb: 2,
      status: "FINISHED",
      day: 91,
    },
    {
      key: "lb-r1-2",
      round: "LB Round 1",
      pos: 2,
      a: 6,
      b: 5,
      sa: 2,
      sb: 1,
      status: "FINISHED",
      day: 91,
    },
    {
      key: "lb-r2-1",
      round: "LB Round 2",
      pos: 1,
      a: 3,
      b: 1,
      sa: 1,
      sb: 2,
      status: "FINISHED",
      day: 92,
    },
    {
      key: "lb-r2-2",
      round: "LB Round 2",
      pos: 2,
      a: 6,
      b: 4,
      sa: 0,
      sb: 2,
      status: "FINISHED",
      day: 92,
    },
    {
      key: "lb-r3",
      round: "LB Round 3",
      pos: 1,
      a: 1,
      b: 4,
      sa: 2,
      sb: 0,
      status: "FINISHED",
      day: 93,
    },
    {
      key: "lb-f",
      round: "LB Finale",
      pos: 1,
      a: 1,
      b: 2,
      sa: 2,
      sb: 1,
      status: "FINISHED",
      day: 93,
    },
    { key: "gf", round: "Grande Finale", pos: 1, a: 0, b: 1, status: "SCHEDULED", day: 94 },
  ],
};

export const SPIKE_TOUR_SEEDS: TournamentSeed[] = [
  SPIKE_TOUR_QUALIFIER_SEED,
  SPIKE_TOUR_PLAYOFFS_SEED,
];

// Garde-fou : une faute de frappe dans un index d'équipe sortirait sinon en
// `undefined` au moment du `createMany`, avec un message Prisma illisible.
for (const seed of SPIKE_TOUR_SEEDS) {
  for (const m of seed.matches) {
    if (TEAM_IDS[m.a] == null || TEAM_IDS[m.b] == null) {
      throw new Error(`${seed.id} : match ${m.key} référence une équipe inconnue`);
    }
  }
}
